def get_alpha_ventage_metrics() -> list[str]:
    return [
      '''  "grossProfit",
        "totalRevenue",
        "costOfRevenue",
        "costofGoodsAndServicesSold",
        "operatingIncome",
        "sellingGeneralAndAdministrative",
        "researchAndDevelopment",
        "operatingExpenses",
        "investmentIncomeNet",
        "netInterestIncome",
        "interestIncome",
        "interestExpense",
        "nonInterestIncome",
        "otherNonOperatingIncome",
        "depreciation",
        "depreciationAndAmortization",
        "incomeBeforeTax",
        "incomeTaxExpense",
        "interestAndDebtExpense",
        "netIncomeFromContinuingOperations",
        "comprehensiveIncomeNetOfTax",
        "ebit",
        "ebitda",
        "netIncome",
        "operatingCashflow",
        "paymentsForOperatingActivities",
        "proceedsFromOperatingActivities",
        "changeInOperatingLiabilities",
        "changeInOperatingAssets",
        "depreciationDepletionAndAmortization",
        "capitalExpenditures",
        "changeInReceivables",
        "changeInInventory",
        "profitLoss",
        "cashflowFromInvestment",
        "cashflowFromFinancing",
        "proceedsFromRepaymentsOfShortTermDebt",
        "paymentsForRepurchaseOfCommonStock",
        "paymentsForRepurchaseOfEquity",
        "paymentsForRepurchaseOfPreferredStock",
        "dividendPayout",
        "dividendPayoutCommonStock",
        "dividendPayoutPreferredStock",
        "proceedsFromIssuanceOfCommonStock",
        "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet",
        "proceedsFromIssuanceOfPreferredStock",
        "proceedsFromRepurchaseOfEquity",
        "proceedsFromSaleOfTreasuryStock",
        "stockBasedCompensation",
        "changeInCashAndCashEquivalents",
        "changeInExchangeRate",
        "netIncome",
        "totalAssets",
        "totalCurrentAssets",
        "cashAndCashEquivalentsAtCarryingValue",
        "cashAndShortTermInvestments",
        "inventory",
        "currentNetReceivables",
        "totalNonCurrentAssets",
        "propertyPlantEquipment",
        "accumulatedDepreciationAmortizationPPE",
        "intangibleAssets",
        "intangibleAssetsExcludingGoodwill",
        "goodwill",
        "investments",
        "longTermInvestments",
        "shortTermInvestments",
        "otherCurrentAssets",
        "otherNonCurrentAssets",
        "totalLiabilities",
        "totalCurrentLiabilities",
        "currentAccountsPayable",
        "deferredRevenue",
        "currentDebt",
        "shortTermDebt",
        "totalNonCurrentLiabilities",
        "capitalLeaseObligations",
        "longTermDebt",
        "currentLongTermDebt",
        "longTermDebtNoncurrent",
        "shortLongTermDebtTotal",
        "otherCurrentLiabilities",
        "otherNonCurrentLiabilities",
        "totalShareholderEquity",
        "treasuryStock",
        "retainedEarnings",
        "commonStock",
        "commonStockSharesOutstanding",'''
    ]


def get_fmp_metrics() -> list[str]:
    return [
        "costOfRevenue"
    ]


def get_guro_metrics() -> list[str]:
    return [
      '''  "capex_to_operating_cash_flow",
        "capex_to_operating_income",
        "capex_to_revenue",
        "cash_ratio",
        "cash_conversion_cycle",
        "interest_coverage",
        "total_liabilities",
        "total_current_liabilities",
        "total_free_cash_flow",
        "total_current_assets",
        "total_non_current_assets",
        "total_assets",
        "cash_and_cash_equivalents",
        "total_equity",
        "cost_of_goods_sold_to_revenue",
        "cost_of_goods_sold",
        "accounts_payable",
        "current_ratio",
        "days_inventory",
        "days_payable",
        "days_sales_outstanding",
        "debt_to_asset",
        "debt_to_equity",
        "degree_of_financial_leverage",
        "degree_of_operating_leverage",
        "ebitda_margin",
        "ebit",
        "enterprise_value_to_ebit",
        "enterprise_value_to_ebitda",
        "enterprise_value_to_fcf",
        "enterprise_value_to_ocf",
        "enterprise_value_to_revenue",
        "equity_to_asset",
        "fcf_margin",
        "fcf_yield",
        "fscore",
        "gf_score",
        "gf_value",
        "graham_number",
        "gross_margin",
        "price_to_gf_value",
        "mscore",
        "gross_profit_to_asset",
        "inventory_to_revenue",
        "inventory_turnover",
        "net_margin",
        "ocf_margin",
        "ocf_yield",
        "yield",
        "operating_margin",
        "pb_ratio",
        "pe_ratio",
        "peg_ratio",
        "peter_lynch_fair_value",
        "ps_ratio",
        "quick_ratio",
        "rank_balancesheet",
        "rank_gf_value",
        "rank_growth",
        "rank_momentum",
        "rank_predictability",
        "rank_profitability",
        "rd2rev",
        "receivables_turnover",
        "return_on_tangible_asset",
        "return_on_tangible_equity",
        "roa",
        "roce",
        "roe",
        "roic",
        "shiller_pe_ratio",
        "sloan_ratio",
        "snoa",
        "total_employee_number",
        "turnover",
        "wacc",
        "zscore",
        "cash_per_share",
        "ebitda_per_share",
        "free_cash_flow_per_share",
        "growth_per_share_ebitda",
        "growth_per_share_eps",
        "net_cash_per_share",
        "price_to_free_cash_flow",
        "price_to_operating_cash_flow",
        "price_to_owner_earnings",
        "price_to_tangible_book",
        "revenue_per_share",
        "revenue",
        "good_will",
        "intangibles",
        "defensive_interval_ratio"'''
    ]

def get_considered_financial_metric_of_pip_sources() -> list[str]:
    return [
        "Gross Margin",
        "Operating Margin",
        "Net Profit Margin",
        "Interest Coverage Ratio",
        "Income Before Tax Profit Margin",
        "Effective Tax Rate",
        "Return on Assets",
        "Return on Equity",
        "Return on Invested Capital",
        "Return on Capital Employed",
        "Return on Tangible Assets"
        "Income Quality Ratio",
        "Free Cash Flow to Operating Cash Flow Ratio",
        "EBIT to Revenue",
        "Days of Inventory Outstanding",
        "Days of Sales Outstanding",
        "Operating Cycle",
        "Days of Accounts Payable Outstanding",
        "Cash Conversion Cycle",
        "Cash Conversion Efficiency",
        "Receivables Turnover",
        "Inventory Turnover Ratio",
        "Accounts Payable Turnover Ratio",
        "SGA-to-Revenue Ratio",
        "Fixed Asset Turnover",
        "Asset Turnover Ratio",
        "Operating Ratio",
        "Current Ratio",
        "Quick Ratio",
        "Cash Ratio",
        "Working Capital",
        "Operating Cash Flow Ratio",
        "Operating Cash Flow to Sales Ratio",
        "Short Term Coverage Ratio",
        "Debt-to-Assets Ratio",
        "Debt-to-Equity Ratio",
        "Debt Service Coverage Ratio",
        "Free Cash Flow Yield",
        "Net-Debt to EBITDA Ratio",
        "Cash Flow Coverage Ratio",
        "Dividend CAPEX Coverage Ratio",
        "Earnings per Share",
        "Revenue per Share",
        "Price-to-Earnings",
        "Price-to-Earnings-Growth",
        "Book Value per Share",
        "Price-to-Book",
        "Price-to-Cash-Flow",
        "Price-to-Free-Cash-Flow",
        "EV-to-Sales",
        "EV-to-EBIT",
        "EV-to-EBITDA",
        "EV-to-Operating-Cash-Flow",
        "Piotroski Score",
        "Altman Z-Score"
    ]

def metric_will_be_considered(metric: str, financial_metrics_to_consider:list[str]) -> bool:
    return metric in financial_metrics_to_consider

def merge_all_financial_metrics_map(*maps: dict) -> dict:
    result = {}
    for m in maps:
        for k, v in m.items():
            result.setdefault(k, v)
    return result

