def get_alpha_ventage_metrics() -> list[str]:
    return [
        "grossProfit",
        "totalRevenue",
        "costOfRevenue",
        "costofGoodsAndServicesSold",
        "operatingIncome",
        "sellingGeneralAndAdministrative",
        "researchAndDevelopment",
        "operatingExpenses",
        "investmentIncomeNet",
        "netInterestIncome",
        "interestIncome",
        "interestExpense",
        "nonInterestIncome",
        "otherNonOperatingIncome",
        "depreciation",
        "depreciationAndAmortization",
        "incomeBeforeTax",
        "incomeTaxExpense",
        "interestAndDebtExpense",
        "netIncomeFromContinuingOperations",
        "comprehensiveIncomeNetOfTax",
        "ebit",
        "ebitda",
        "netIncome",
        "operatingCashflow",
        "paymentsForOperatingActivities",
        "proceedsFromOperatingActivities",
        "changeInOperatingLiabilities",
        "changeInOperatingAssets",
        "depreciationDepletionAndAmortization",
        "capitalExpenditures",
        "changeInReceivables",
        "changeInInventory",
        "profitLoss",
        "cashflowFromInvestment",
        "cashflowFromFinancing",
        "proceedsFromRepaymentsOfShortTermDebt",
        "paymentsForRepurchaseOfCommonStock",
        "paymentsForRepurchaseOfEquity",
        "paymentsForRepurchaseOfPreferredStock",
        "dividendPayout",
        "dividendPayoutCommonStock",
        "dividendPayoutPreferredStock",
        "proceedsFromIssuanceOfCommonStock",
        "proceedsFromIssuanceOfLongTermDebtAndCapitalSecuritiesNet",
        "proceedsFromIssuanceOfPreferredStock",
        "proceedsFromRepurchaseOfEquity",
        "proceedsFromSaleOfTreasuryStock",
        "stockBasedCompensation",
        "changeInCashAndCashEquivalents",
        "changeInExchangeRate",
        "netIncome",
        "totalAssets",
        "totalCurrentAssets",
        "cashAndCashEquivalentsAtCarryingValue",
        "cashAndShortTermInvestments",
        "inventory",
        "currentNetReceivables",
        "totalNonCurrentAssets",
        "propertyPlantEquipment",
        "accumulatedDepreciationAmortizationPPE",
        "intangibleAssets",
        "intangibleAssetsExcludingGoodwill",
        "goodwill",
        "investments",
        "longTermInvestments",
        "shortTermInvestments",
        "otherCurrentAssets",
        "otherNonCurrentAssets",
        "totalLiabilities",
        "totalCurrentLiabilities",
        "currentAccountsPayable",
        "deferredRevenue",
        "currentDebt",
        "shortTermDebt",
        "totalNonCurrentLiabilities",
        "capitalLeaseObligations",
        "longTermDebt",
        "currentLongTermDebt",
        "longTermDebtNoncurrent",
        "shortLongTermDebtTotal",
        "otherCurrentLiabilities",
        "otherNonCurrentLiabilities",
        "totalShareholderEquity",
        "treasuryStock",
        "retainedEarnings",
        "commonStock",
        "commonStockSharesOutstanding",
        "MarketCapitalization"
    ]


def get_fmp_metrics() -> list[str]:
    return [
        "costOfRevenue"
    ]


def get_guro_metrics() -> list[str]:
    return [
        "capex_to_operating_cash_flow",
        "capex_to_operating_income",
        "capex_to_revenue",
        "cash_ratio",
        "cost_of_goods_sold_to_revenue",
        "current_ratio",
        "days_inventory",
        "days_payable",
        "days_sales_outstanding",
        "debt_to_asset",
        "debt_to_equity",
        "degree_of_financial_leverage",
        "degree_of_operating_leverage",
        "ebitda_margin",
        "enterprise_value_to_ebit",
        "enterprise_value_to_ebitda",
        "enterprise_value_to_fcf",
        "enterprise_value_to_ocf",
        "enterprise_value_to_revenue",
        "equity_to_asset",
        "fcf_margin",
        "fcf_yield",
        "fscore",
        "gf_score",
        "gf_value",
        "graham_number",
        "gross_margin",
        "gross_profit_to_asset",
        "inventory_to_revenue",
        "inventory_turnover",
        "net_margin",
        "ocf_margin",
        "ocf_yield",
        "operating_margin",
        "pb_ratio",
        "pe_ratio",
        "peg_ratio",
        "peter_lynch_fair_value",
        "ps_ratio",
        "quick_ratio",
        "rank_balancesheet",
        "rank_gf_value",
        "rank_growth",
        "rank_momentum",
        "rank_predictability",
        "rank_profitability",
        "rd2rev",
        "receivables_turnover",
        "return_on_tangible_asset",
        "return_on_tangible_equity",
        "roa",
        "roce",
        "roe",
        "roic",
        "shiller_pe_ratio",
        "sloan_ratio",
        "snoa",
        "total_employee_number",
        "turnover",
        "wacc",
        "zscore"
    ]

def metric_will_be_considered(metric: str, financial_metrics_to_consider:list[str]) -> bool:
    return metric in financial_metrics_to_consider

def merge_all_financial_metrics_map(*maps: dict) -> dict:
    result = {}
    for m in maps:
        for k, v in m.items():
            result.setdefault(k, v)
    return result
