from typing import Union, List, Tuple, Any


def get_all_used_categories_for_eval(category_satisfied_map: dict[str, list])->list[str]:
    if isinstance(category_satisfied_map, dict):
        return list(category_satisfied_map.keys())
    elif isinstance(category_satisfied_map, list) and all(isinstance(i, tuple) for i in category_satisfied_map):
        return [item[0] for item in category_satisfied_map]
    else:
        raise TypeError("Unsupported type")


def get_each_metrics_list_by_category(
        category : str,
        category_satisfied_map: dict[str, list],
                                    category_unsatisfied_map: dict[str, list],
                                    category_satisfied_only_reference_value_map: dict[str, list],
                                    category_unsatisfied_only_reference_value_map: dict[str, list],
                                    category_satisfied_only_development_map: dict[str, list],
                                    category_unsatisfied_development_map: dict[str, list],
                                      )->(list[str],
                                                                                 list[str],
                                                                                 list[str],
                                                                                 list[str],
                                                                                 list[str],
                                                                                 list[str]):

    return (
        get_translated_metric_list(convert_into_dictionary_if_necessary(category_satisfied_map).get(category, [])),
        get_translated_metric_list(convert_into_dictionary_if_necessary(category_unsatisfied_map).get(category, [])),
        get_translated_metric_list(convert_into_dictionary_if_necessary(category_satisfied_only_reference_value_map).get(category, [])),
        get_translated_metric_list(convert_into_dictionary_if_necessary(category_unsatisfied_only_reference_value_map).get(category, [])),
        get_translated_metric_list(convert_into_dictionary_if_necessary(category_satisfied_only_development_map).get(category, [])),
        get_translated_metric_list(convert_into_dictionary_if_necessary(category_unsatisfied_development_map).get(category, [])),
    )

def convert_into_dictionary_if_necessary(maybe_dict: Union[dict, List[Tuple[Any, Any]]]) -> dict:
    if isinstance(maybe_dict, dict):
        return maybe_dict
    if isinstance(maybe_dict, list):
        try:
            return dict(maybe_dict)
        except Exception as e:
            raise TypeError(f"List cannot be converted to dict: {e}")
    raise TypeError(f"Expected dict or list of tuples, got {type(maybe_dict)}")

def get_translated_metric_list(financial_metric_list: list[str])-> list[str]:

    return [get_translation_of_metric_if_input_is_metric(fin_metric) for fin_metric in financial_metric_list]


def get_translation_of_metric_if_input_is_metric(word: str):
    financial_metric_map = get_financial_metric_translation_map()
    return financial_metric_map.get(word, word)

def get_financial_metric_translation_map()->dict[str, str]:
    return {
        "cash_conversion_efficiency": "Cash Conversion Effizienz",
        "operating_cycle": "Operations Zyklus",
        "operating_ratio": "Operations Ratio",
        "sga_to_revenue": "SGA im Vergleich zu Umsatz",
        "fixed_asset_turnover": "Umschlagshäufigkeit der Anlagen",
        "asset_turnover": "Anlagen Überschlag",
        "earnings_per_share": "Verdienst pro Aktie",
        "price_to_cashflow": "Kurs zu Cashflow Verhältnis",
        "dividend_paid_and_capex_coverage_ratio": "Dividenden und Investitions Deckung",
        "cash_flow_coverage_ratio": "Cashflow zu Schulden",
        "debt_service_coverage_ratio": "Schuldendienstdeckungsgrad",
        "net_debt_to_ebitda": "Netto Schulden/ Ebitda",
        "effective_tax_rate": "effektive Steuerrate",
        "short_term_coverage_ratio": "Umlaufvermögen / kurzfristige schulden",
        "ebit_margin": "EBIT margin",
        "free_cashflow_operating_cashflow_ratio": "Free cashflow zu operativen cashflow",
        "income_before_tax_profit_margin": "Umsatzrendite vor Steuern",
        "operating_cashflow_ratio": "Operativer cashflow zu kurzfristige Schulden",
        "operating_cashflow_sales_ratio": "Operativer cashflow zu Umsatz",
        "wacc": "WACC (Gewichtete Kapitalkosten)",
        "net_ppe": "Netto-Sachanlagen",
        "snoa": "Strategisches Netto-Betriebsvermögen (SNOA)",
        "intangiblesToTotalAssets": "Immaterielle Vermögenswerte zu Bilanzsumme",
        "enterprise_value_to_ebit": "Enterprise Value zu EBIT (EV/EBIT)",
        "enterprise_value_to_ebitda": "Enterprise Value zu EBITDA (EV/EBITDA)",
        "enterprise_value_to_fcf": "Enterprise Value zu Free Cashflow (EV/FCF)",
        "enterprise_value_to_ocf": "Enterprise Value zu operativem Cashflow (EV/OCF)",
        "enterprise_value_to_revenue": "Enterprise Value zu Umsatz (EV/Sales)",
        "pb_ratio": "Kurs-Buchwert-Verhältnis (KBV)",
        "pe_ratio": "Kurs-Gewinn-Verhältnis (KGV)",
        "peg_ratio": "PEG-Verhältnis (KGV zu Gewinnwachstum)",
        "price_to_free_cash_flow": "Kurs-Free-Cashflow-Verhältnis",
        "price_to_gf_value": "Kurs zu GF-Value",
        "price_to_operating_cash_flow": "Kurs-Cashflow-Verhältnis (KCV)",
        "price_to_owner_earnings": "Kurs zu Eigentümer-Gewinn (Owner Earnings)",
        "price_to_tangible_book": "Kurs zu materiellem Buchwert",
        "ps_ratio": "Kurs-Umsatz-Verhältnis (KUV)",
        "rank_balancesheet": "Bilanz-Ranking",
        "rank_gf_value": "GF-Value-Ranking",
        "rank_growth": "Wachstums-Ranking",
        "rank_momentum": "Momentum-Ranking",
        "rank_predictability": "Vorhersehbarkeits-Ranking",
        "rank_profitability": "Rentabilitäts-Ranking",
        "shiller_pe_ratio": "Shiller-KGV (CAPE)",
        "priceToEarningsRatio": "Kurs-Gewinn-Verhältnis (KGV)",
        "priceToEarningsGrowthRatio": "PEG-Verhältnis",
        "forwardPriceToEarningsGrowthRatio": "Erwartetes PEG-Verhältnis (Forward PEG)",
        "priceToBookRatio": "Kurs-Buchwert-Verhältnis (KBV)",
        "priceToSalesRatio": "Kurs-Umsatz-Verhältnis (KUV)",
        "priceToFreeCashFlowRatio": "Kurs-Free-Cashflow-Verhältnis",
        "priceToOperatingCashFlowRatio": "Kurs-Cashflow-Verhältnis (KCV)",
        "cost_of_goods_sold_to_revenue": "Herstellungskostenquote am Umsatz",
        "ebitda_margin": "EBITDA-Marge",
        "fcf_margin": "Free-Cashflow-Marge",
        "free_cash_flow_per_share": "Free Cashflow je Aktie",
        "gross_margin": "Bruttomarge",
        "gross_profit_to_asset": "Bruttogewinn zu Gesamtvermögen",
        "growth_per_share_ebitda": "EBITDA-Wachstum je Aktie",
        "growth_per_share_eps": "Gewinnwachstum (EPS) je Aktie",
        "growth_revenue_per_share": "Umsatzwachstum je Aktie",
        "inventory_to_revenue": "Lagerbestand im Verhältnis zum Umsatz",
        "net_margin": "Nettomarge",
        "ocf_margin": "Operative Cashflow-Marge",
        "ocf_yield": "Operative Cashflow-Rendite",
        "operating_margin": "Operative Marge (EBIT-Marge)",
        "rate_of_return_value": "Renditewert",
        "return_on_tangible_equity": "Materiell Eigenkapitalrendite (ROTE)",
        "roa": "Gesamtkapitalrendite (ROA)",
        "roce": "Rendite auf das eingesetzte Kapital (ROCE)",
        "roe": "Eigenkapitalrendite (ROE)",
        "roic": "Rendite auf das investierte Kapital (ROIC)",
        "freeCashFlowToEquity": "Free Cashflow to Equity (FCFE)",
        "ebitMargin": "EBIT-Marge",
        "operatingProfitMargin": "Betriebsergebnismarge",
        "pretaxProfitMargin": "EBT-Marge (Vorsteuer-Marge)",
        "netProfitMargin": "Nettogewinnmarge",
        "workingCapitalTurnoverRatio": "Working Capital Umschlagshäufigkeit",
        "operatingCashFlowSalesRatio": "Operativer Cashflow zu Umsatz",
        "freeCashFlowOperatingCashFlowRatio": "Free Cashflow zu operativem Cashflow",
        "revenue_per_employee": "Umsatz pro Mitarbeiter",
        "dividends": "Dividenden",
        "dividends_per_share": "Dividende je Aktie",
        "is_preferred_dividends": "Vorzugsdividenden",
        "degree_of_financial_leverage": "Finanzieller Hebelgrad (DFL)",
        "degree_of_operating_leverage": "Operativer Hebelgrad (DOL)",
        "fscore": "Piotroski F-Score",
        "piotroski": "Piotroski Score",
        "gf_score": "GF Score",
        "gf_value": "GF Value",
        "graham_number": "Graham-Nummer",
        "mscore": "Beneish M-Score",
        "peter_lynch_fair_value": "Fairer Wert nach Peter Lynch",
        "zscore": "Altman Z-Score",
        "financialLeverageRatio": "Finanzierungshebel",
        "debt_to_asset": "Schulden/Gesamtvermögen",
        "debt_to_equity": "Schulden zu Eigenkapital",
        "defensive_interval_ratio": "Defensive Interval Ratio (Reichweite der Liquidität)",
        "equity_to_asset": "Eigenkapitalquote",
        "fcf_yield": "Free Cashflow-Rendite",
        "interest_coverage": "Zinsdeckungsgrad",
        "liabilities_to_assets": "Fremdkapitalquote",
        "net_issuance_of_debt": "Netto-Neuverschuldung",
        "net_net_working_capital": "Net-Net Working Capital (NNWC)",
        "sloan_ratio": "Sloan-Ratio (Bilanzqualität)",
        "solvencyRatio": "Solvenzquote",
        "debtToAssetsRatio": "Schulden-Vermögens-Verhältnis",
        "debtToEquityRatio": "Verschuldungsgrad (Schulden/Eigenkapital)",
        "debtToCapitalRatio": "Schulden-Kapital-Verhältnis",
        "longTermDebtToCapitalRatio": "Langfristige Schulden zum Gesamtkapital",
        "operatingCashFlowRatio": "Operative Cashflow-Quote",
        "debtServiceCoverageRatio": "Schuldendienstdeckungsgrad (DSCR)",
        "interestCoverageRatio": "Zinsdeckungsgrad (ICR)",
        "shortTermOperatingCashFlowCoverageRatio": "Kurzfristige Deckung durch operativen Cashflow",
        "operatingCashFlowCoverageRatio": "Operative Cashflow-Deckungsquote",
        "capitalExpenditureCoverageRatio": "Investitionsdeckungsquote (Capex Coverage)",
        "dividendPaidAndCapexCoverageRatio": "Dividenden- und Capex-Deckungsquote",
        "gearing": "Verschuldungsgrad (Gearing)",
        "netDebtToEBITDA": "Nettofinanzschulden zu EBITDA",
        "dynamic debt degree": "Dynamischer Verschuldungsgrad",
        "current_asset_intensity": "Umlaufvermögensintensität",
        "non_current_asset_intensity": "Anlagevermögensintensität",
        "asset_cover_ratio_one": "Anlagendeckungsgrad I",
        "asset_cover_ratio_two": "Anlagendeckungsgrad II",
        "good_will_ratio": "Goodwill-Quote",
        "capex_to_depreciation": "Wachstumsquote",
        "financial_leverage_ratio": "Verbindlichkeiten zu Eigenkapital",
        "long_term_debt_to_capital_ratio": "lang. Schulden zu lang Schulden und Eigenkapital",
        "intangibles_to_total_assets": "Verhältnis von immateriellen Vermögenswerten zum Gesamtvermögen",
        "income_quality_ratio": "Einkommensqualität (Operativer cashflow zu Rein Gewinn)",
        "cash_ratio": "Liquiditätsgrad 1",
        "current_ratio": "Liquiditätsgrad 3",
        "days_inventory": "Lagerdauer (in Tagen)",
        "days_payable": "Zahlungsziel Verbindlichkeiten (in Tagen)",
        "days_sales_outstanding": "Forderungslaufzeit (DSO in Tagen)",
        "inventory_turnover": "Lagerumschlagshäufigkeit",
        "quick_ratio": "Liquiditätsgrad 2",
        "receivables_turnover": "Forderungsumschlag",
        "daysOfPayablesOutstanding": "Zahlungsziel der Verbindlichkeiten (DPO)",
        "daysOfInventoryOutstanding": "Lagerdauer (DIO)",
        "payablesTurnover": "Kreditorenumschlagshäufigkeit",
        "fixedAssetTurnover": "Anlagenumschlagshäufigkeit",
        "capex_to_operating_cash_flow": "Sachinvestitionsquote",
        "capex_to_operating_income": "Capex zum Betriebsergebnis",
        "capex_to_revenue": "Investitionsquote (Capex zu Umsatz)",
        "rd2rev": "F&E-Quote (Forschungs- und Entwicklungskosten zu Umsatz)",
        "salesGeneralAndAdministrativeToRevenue": "Vertriebs- und Verwaltungskostenquote (Vertrieb/Verwaltung zu Umsatz)",
        "researchAndDevelopementToRevenue": "F&E-Aufwendungen zu Umsatz",
        "capexToDepreciation": "Investitionen zu Abschreibungen (Capex/AfA)",
        "accounts_payable": "Verbindlichkeiten aus Lieferungen und Leistungen",
        "accounts_payable_accrued_expense": "Verbindlichkeiten aus L&L und passive Rechnungsabgrenzung",
        "accounts_receivable": "Forderungen aus Lieferungen und Leistungen",
        "accumulated_depreciation": "Kumulierte Abschreibungen",
        "accumulated_other_comprehensive_income": "Kumuliertes sonstiges Eigenkapital (AOCI)",
        "additional_paid_in_capital": "Kapitalrücklage",
        "asset_impairment_charge": "Wertminderungsaufwendungen (Impairment)",
        "beginning_cash_position": "Finanzmittelbestand zu Beginn der Periode",
        "beta": "Beta-Faktor",
        "book_value_per_share": "Buchwert je Aktie",
        "bs_current_deferred_liabilities": "Kurzfristige passive Rechnungsabgrenzungsposten / Steuerabgrenzung",
        "bs_share": "Bilanzanteil",
        "buildings_and_improvements": "Bauten und Gebäudeinvestitionen",
        "buyback_yield": "Aktienrückkauf-Rendite",
        "cash_and_cash_equivalents": "Flüssige Mittel (Cash und Cash-Äquivalente)",
        "cash_conversion_cycle": "Geldumschlagzyklus (Cash Conversion Cycle)",
        "cash_equivalents_marketable_securities": "Zahlungsmitteläquivalente und Wertpapiere des Umlaufvermögens",
        "cash_flow_capital_expenditure": "Cashflow für Investitionen (Capex)",
        "cash_flow_deferred_tax": "Cashflow aus latente Steuern",
        "cash_flow_depreciation_depletion_amortization": "Cashflow-wirksame Abschreibungen (AfA)",
        "cash_flow_for_lease_financing": "Cashflow aus Leasingfinanzierung",
        "cash_flow_from_investing": "Cashflow aus der Investitionstätigkeit",
        "cash_flow_from_operations": "Cashflow aus der Geschäftstätigkeit (Operativer Cashflow)",
        "cash_flow_from_operations_per_share": "Operativer Cashflow je Aktie",
        "cash_flow_from_others": "Sonstiger Cashflow",
        "cash_from_discontinued_investing_activities": "Investitions-Cashflow aus aufgegebenen Geschäftsbereichen",
        "cash_from_discontinued_operating_activities": "Operativer Cashflow aus aufgegebenen Geschäftsbereichen",
        "cash_from_financing": "Cashflow aus der Finanzierungstätigkeit",
        "cash_from_other_investing_activities": "Cashflow aus sonstigen Investitionsaktivitäten",
        "cash_per_share": "Flüssige Mittel je Aktie",
        "revenue_per_share": "Umsatz je Aktie",
        "turnover": "Umsatz / Umschlag",
        "work_in_process": "Unfertige Erzeugnisse",
        "yield": "Rendite",
        "freeCashFlowToFirm": "Free Cashflow to Firm (FCFF)",
        "cost_of_goods_and_service_sold_to_revenue": "Materialkostenaufwand",
        "cost_of_revenue_to_revenue": "Umsatzkostenquote",
        "research_and_developement_to_revenue": "Forschung und Entwicklungskosten- Aufwand",
        "sales_general_and_administrative_to_revenue": "Vertriebs und Verwaltungskosten Aufwand",
        "cash_burn_rate": "Cash Burn Rate",
        "dynamic_debt_degree": "Dynamischer Verschuldungsgrad",
        "gross_profit_to_cost": "Bruttogewinn zu Kosten",
        "operating_cashflow_coverage_ratio": "Operativer Cashflow zu Schulden",
        "revenue_to_cost": "Umsatz zu Kosten",
        "short_term_operating_cashflow_coverage_ratio": "Operativer cashflow zu kurzfristigen Verbindlichkeiten",
        "capital_turnover": "Kapitalumschlag",
        "revenue_per_employee_cost": "Umsatz pro Personalkosten  pro Mitarbeiter",
        "roi": "Return on Investment",
        "payables_turnover": "Kreditorenumschlag",
        "debt_to_capital_ratio": "Schulden zu Schulden und Eigenkapital",
        "link_edit": "Kennzahl bearbeiten",
    }