"""add ticker to watchlist stocks

Revision ID: 4885bf084c6c
Revises: 621d102834d1
Create Date: 2026-05-29 10:02:13.803386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4885bf084c6c'
down_revision: Union[str, Sequence[str], None] = '621d102834d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('stock_summary', sa.Column('ticker', sa.String(), nullable=True))
    #op.create_index(op.f('ix_stock_summary_ticker'), 'stock_summary', ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
