"""adjust bought_stock constraints

Revision ID: 5bca0e1dc4c7
Revises: fe642ad934a2
Create Date: 2026-05-25 22:07:20.261232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bca0e1dc4c7'
down_revision: Union[str, Sequence[str], None] = 'fe642ad934a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bought_stock_name'), table_name='bought_stock')
    op.create_index(op.f('ix_bought_stock_name'), 'bought_stock', ['name'], unique=False)
    op.drop_index(op.f('ix_bought_stock_ticker'), table_name='bought_stock')
    op.create_index(op.f('ix_bought_stock_ticker'), 'bought_stock', ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_bought_stock_ticker'), table_name='bought_stock')
    op.create_index(op.f('ix_bought_stock_ticker'), 'bought_stock', ['ticker'], unique=1)
    op.drop_index(op.f('ix_bought_stock_name'), table_name='bought_stock')
    op.create_index(op.f('ix_bought_stock_name'), 'bought_stock', ['name'], unique=1)
    # ### end Alembic commands ###
