"""do wiki page col and strengt and weakness also in bougth stock

Revision ID: 621d102834d1
Revises: 81579e21fc82
Create Date: 2026-05-28 18:17:00.710019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621d102834d1'
down_revision: Union[str, Sequence[str], None] = '81579e21fc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
  #  op.add_column('bought_stock', sa.Column('strengths', sa.Text(), nullable=True))
  #  op.add_column('bought_stock', sa.Column('weaknesses', sa.Text(), nullable=True))
  #  op.add_column('bought_stock', sa.Column('wiki_page', sa.Text(), nullable=True))
  #  op.add_column('stock_summary', sa.Column('wiki_page', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

  #  op.drop_column('stock_summary', 'wiki_page')
   # op.drop_column('bought_stock', 'wiki_page')
   # op.drop_column('bought_stock', 'weaknesses')
   # op.drop_column('bought_stock', 'strengths')
    # ### end Alembic commands ###
