"""add metric can be selected to a category

Revision ID: 7719e6fcf2b8
Revises: 895709b3fa4a
Create Date: 2026-05-11 09:32:16.167258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7719e6fcf2b8'
down_revision: Union[str, Sequence[str], None] = '895709b3fa4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metric', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_metric', 'category')
    # ### end Alembic commands ###
