"""add 1:n rel financial metric and category  

Revision ID: 794637a1a808
Revises: 8fd94fb9b61a
Create Date: 2026-05-14 22:45:59.906511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794637a1a808'
down_revision: Union[str, Sequence[str], None] = '8fd94fb9b61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'financial_metric_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        if_not_exists=True,
    )





    with op.batch_alter_table('financial_metric', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_financial_metric_category',
            'financial_metric_category',
            ['category_id'],
            ['id']
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'financial_metric', type_='foreignkey')
    op.drop_column('financial_metric', 'category_id')
    op.drop_index(op.f('ix_financial_metric_category_name'), table_name='financial_metric_category')
    op.drop_index(op.f('ix_financial_metric_category_id'), table_name='financial_metric_category')
    op.drop_table('financial_metric_category')
    # ### end Alembic commands ###
