"""add is calculate col for fin metric table

Revision ID: 81579e21fc82
Revises: 5bca0e1dc4c7
Create Date: 2026-05-26 08:26:41.559839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81579e21fc82'
down_revision: Union[str, Sequence[str], None] = '5bca0e1dc4c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.add_column('financial_metric', sa.Column('is_calculated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""

    #op.drop_column('financial_metric', 'is_calculated')
    # ### end Alembic commands ###
