"""rm calculate col

Revision ID: 82cc24708e23
Revises: 4885bf084c6c
Create Date: 2026-06-08 14:46:30.399526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cc24708e23'
down_revision: Union[str, Sequence[str], None] = '4885bf084c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.drop_column('financial_metric', 'is_calculated')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
