"""recreate schema

Revision ID: 895709b3fa4a
Revises: 612cd381bb6a
Create Date: 2026-04-28 20:08:31.100009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895709b3fa4a'
down_revision: Union[str, Sequence[str], None] = '612cd381bb6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('should_rise', sa.Boolean(), nullable=True),
    sa.Column('reference_value', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metric_id'), 'financial_metric', ['id'], unique=False)
    op.create_index(op.f('ix_financial_metric_name'), 'financial_metric', ['name'], unique=True)
    op.create_table('stock_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_summary_id'), 'stock_summary', ['id'], unique=False)
    op.create_index(op.f('ix_stock_summary_name'), 'stock_summary', ['name'], unique=True)
    op.create_index(op.f('ix_stock_summary_strength'), 'stock_summary', ['strength'], unique=False)
    op.create_index(op.f('ix_stock_summary_weakness'), 'stock_summary', ['weakness'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_summary_weakness'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_strength'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_name'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_id'), table_name='stock_summary')
    op.drop_table('stock_summary')
    op.drop_index(op.f('ix_financial_metric_name'), table_name='financial_metric')
    op.drop_index(op.f('ix_financial_metric_id'), table_name='financial_metric')
    op.drop_table('financial_metric')
    # ### end Alembic commands ###
