"""add display name ref value

Revision ID: 89abb87f68d7
Revises: d32b26d05952
Create Date: 2026-05-17 00:39:18.029706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89abb87f68d7'
down_revision: Union[str, Sequence[str], None] = 'd32b26d05952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metric', sa.Column('display_name_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_metric', 'display_name_reference')
    # ### end Alembic commands ###
