"""add boolean will be visible on wachtlist

Revision ID: 91a81cc43491
Revises: 57b117abf96e
Create Date: 2026-05-21 19:05:19.615049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a81cc43491'
down_revision: Union[str, Sequence[str], None] = '57b117abf96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_summary', sa.Column('is_on_watch_list', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_summary', 'is_on_watch_list')
    # ### end Alembic commands ###
