"""add is active col in fin metric

Revision ID: 940637b3bebd
Revises: 
Create Date: 2026-04-28 20:00:12.357870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '940637b3bebd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_summary_id'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_name'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_strength'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_weakness'), table_name='stock_summary')
    op.drop_table('stock_summary')
    op.drop_index(op.f('ix_financial_metric_id'), table_name='financial_metric')
    op.drop_index(op.f('ix_financial_metric_name'), table_name='financial_metric')
    op.drop_table('financial_metric')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_metric',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('should_rise', sa.BOOLEAN(), nullable=True),
    sa.Column('reference_value', sa.INTEGER(), nullable=True),
    sa.Column('unit', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metric_name'), 'financial_metric', ['name'], unique=1)
    op.create_index(op.f('ix_financial_metric_id'), 'financial_metric', ['id'], unique=False)
    op.create_table('stock_summary',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('strength', sa.VARCHAR(), nullable=True),
    sa.Column('weakness', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_summary_weakness'), 'stock_summary', ['weakness'], unique=False)
    op.create_index(op.f('ix_stock_summary_strength'), 'stock_summary', ['strength'], unique=False)
    op.create_index(op.f('ix_stock_summary_name'), 'stock_summary', ['name'], unique=1)
    op.create_index(op.f('ix_stock_summary_id'), 'stock_summary', ['id'], unique=False)
    # ### end Alembic commands ###
