"""add user_id to industry

Revision ID: 947c2cd2c7f5
Revises: 2a66624f515f
Create Date: 2026-06-20 22:22:01.550160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947c2cd2c7f5'
down_revision: Union[str, Sequence[str], None] = '2a66624f515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry', sa.Column('user_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_industry_industry_name'), table_name='industry')
    op.create_index(op.f('ix_industry_industry_name'), 'industry', ['industry_name'], unique=False)
    op.create_foreign_key(None, 'industry', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_constraint(None, 'industry', type_='foreignkey')
    op.drop_index(op.f('ix_industry_industry_name'), table_name='industry')
    op.create_index(op.f('ix_industry_industry_name'), 'industry', ['industry_name'], unique=1)
    op.drop_column('industry', 'user_id')
    # ### end Alembic commands ###
