"""add user_id to industry

Revision ID: 947c2cd2c7f5
Revises: 2a66624f515f
Create Date: 2026-06-20 22:22:01.550160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947c2cd2c7f5'
down_revision: Union[str, Sequence[str], None] = '2a66624f515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('industry', sa.Column('bear_factors', sa.Text))
    op.add_column('industry', sa.Column('bull_factors', sa.Text))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
