"""add an association table for saving metrics per industry 

Revision ID: c1855e3408be
Revises: 16f4e9c9e0d9
Create Date: 2026-05-15 16:23:34.224717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1855e3408be'
down_revision: Union[str, Sequence[str], None] = '16f4e9c9e0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_profile_id'), 'industry_profile', ['id'], unique=False)
    op.create_index(op.f('ix_industry_profile_name'), 'industry_profile', ['name'], unique=True)
    op.create_table('profile_metric_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('should_rise', sa.Boolean(), nullable=True),
    sa.Column('reference_value', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['financial_metric.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['industry_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'metric_id', name='_profile_metric_uc')
    )
    op.drop_index(op.f('ix_financial_metric_branch_profile_id'), table_name='financial_metric_branch_profile')
    op.drop_index(op.f('ix_financial_metric_branch_profile_name'), table_name='financial_metric_branch_profile')
    op.drop_table('financial_metric_branch_profile')
    op.drop_table('branch_profile_metric_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('branch_profile_metric_link',
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['financial_metric.id'], name=op.f('fk_branch_profile_metric_link_metric'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['financial_metric_branch_profile.id'], name=op.f('fk_branch_profile_metric_link_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'metric_id')
    )
    op.create_table('financial_metric_branch_profile',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metric_branch_profile_name'), 'financial_metric_branch_profile', ['name'], unique=1)
    op.create_index(op.f('ix_financial_metric_branch_profile_id'), 'financial_metric_branch_profile', ['id'], unique=False)
    op.drop_table('profile_metric_configuration')
    op.drop_index(op.f('ix_industry_profile_name'), table_name='industry_profile')
    op.drop_index(op.f('ix_industry_profile_id'), table_name='industry_profile')
    op.drop_table('industry_profile')
    # ### end Alembic commands ###
