"""rm col in metric table 

Revision ID: d32b26d05952
Revises: c1855e3408be
Create Date: 2026-05-15 16:36:09.018299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd32b26d05952'
down_revision: Union[str, Sequence[str], None] = 'c1855e3408be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('financial_metric', 'is_active')
    op.drop_column('financial_metric', 'reference_value')
    op.drop_column('financial_metric', 'should_rise')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_metric', sa.Column('should_rise', sa.BOOLEAN(), nullable=True))
    op.add_column('financial_metric', sa.Column('reference_value', sa.INTEGER(), nullable=True))
    op.add_column('financial_metric', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
