"""initial_schema

Revision ID: e1c2be431ff5
Revises: 
Create Date: 2026-05-23 21:07:48.417667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c2be431ff5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_metric_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metric_category_id'), 'financial_metric_category', ['id'], unique=False)
    op.create_index(op.f('ix_financial_metric_category_name'), 'financial_metric_category', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_name'), 'users', ['user_name'], unique=True)
    op.create_table('bought_stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('bought_price', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_stock_ticker')
    )
    op.create_index(op.f('ix_bought_stock_id'), 'bought_stock', ['id'], unique=False)
    op.create_index(op.f('ix_bought_stock_name'), 'bought_stock', ['name'], unique=True)
    op.create_index(op.f('ix_bought_stock_ticker'), 'bought_stock', ['ticker'], unique=True)
    op.create_table('financial_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('display_name_reference', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['financial_metric_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_metric_id'), 'financial_metric', ['id'], unique=False)
    op.create_index(op.f('ix_financial_metric_name'), 'financial_metric', ['name'], unique=True)
    op.create_table('industry_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_stock_ticker')
    )
    op.create_index(op.f('ix_industry_profile_id'), 'industry_profile', ['id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_id'), 'refresh_token', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('stock_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('strength', sa.String(), nullable=True),
    sa.Column('weakness', sa.String(), nullable=True),
    sa.Column('is_on_watch_list', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_stock_ticker')
    )
    op.create_index(op.f('ix_stock_summary_id'), 'stock_summary', ['id'], unique=False)
    op.create_index(op.f('ix_stock_summary_name'), 'stock_summary', ['name'], unique=True)
    op.create_index(op.f('ix_stock_summary_strength'), 'stock_summary', ['strength'], unique=False)
    op.create_index(op.f('ix_stock_summary_weakness'), 'stock_summary', ['weakness'], unique=False)
    op.create_table('profile_metric_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('should_rise', sa.Boolean(), nullable=True),
    sa.Column('reference_value', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['financial_metric.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['industry_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'metric_id', name='_profile_metric_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile_metric_configuration')
    op.drop_index(op.f('ix_stock_summary_weakness'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_strength'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_name'), table_name='stock_summary')
    op.drop_index(op.f('ix_stock_summary_id'), table_name='stock_summary')
    op.drop_table('stock_summary')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_industry_profile_id'), table_name='industry_profile')
    op.drop_table('industry_profile')
    op.drop_index(op.f('ix_financial_metric_name'), table_name='financial_metric')
    op.drop_index(op.f('ix_financial_metric_id'), table_name='financial_metric')
    op.drop_table('financial_metric')
    op.drop_index(op.f('ix_bought_stock_ticker'), table_name='bought_stock')
    op.drop_index(op.f('ix_bought_stock_name'), table_name='bought_stock')
    op.drop_index(op.f('ix_bought_stock_id'), table_name='bought_stock')
    op.drop_table('bought_stock')
    op.drop_index(op.f('ix_users_user_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_financial_metric_category_name'), table_name='financial_metric_category')
    op.drop_index(op.f('ix_financial_metric_category_id'), table_name='financial_metric_category')
    op.drop_table('financial_metric_category')
    # ### end Alembic commands ###
