"""remove unique name at industry profile

Revision ID: ff23f0660284
Revises: 5066f7469b3d
Create Date: 2026-05-23 12:14:08.324760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff23f0660284'
down_revision: Union[str, Sequence[str], None] = '5066f7469b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_industry_profile_name'), table_name='industry_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_industry_profile_name'), 'industry_profile', ['name'], unique=1)
    # ### end Alembic commands ###
